[package]
name = "diplomacy"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
edition = "2018"

[dependencies]
from_variants = "0.4.0"
lazy_static = "1.4.0"
serde = { version = "1.0.112", features = [ "derive" ] }